language: php
php:
- 5.3
- 5.4
- 5.5
before_script:
- wget --quiet http://getcomposer.org/composer.phar
- php composer.phar install --install-suggests
- cp phpunit.xml.dist phpunit.xml
- ~/.nvm/nvm.sh run default vendor/guzzle/guzzle/tests/Guzzle/Tests/Http/server.js
  &
script: phpunit
env:
  global:
    secure: OsTdBqVGrpPsjOf0U6sxFjwli+4752dWLe4QuzDwaCbDIzwEOoRGK6P+ihQJLHih59Q9ckMevjqV84qUyMQF5BbAgtcTJXBpfVI/ga8KT3fp281PaXZXkb7iX5gOgu7zUsMmyfomCju8MoerCVQF59bK4yG0XhXgSrdHk1XzNW4=
